[package]
name = "wordle"
version = "0.1.0"
edition = "2018"
readme = "README.md"
license = "MIT"
author = "cursorsdottsx"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
rand = "0.8.4"
clearscreen = "1.0.9"